import type { Metadata } from "next";
import "@/app/globals.css";
<<<<<<< HEAD:app/(search page)/layout.tsx
import Header from "@/components/header";
import Footer from "@/components/footer";
=======
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";
>>>>>>> 04b78bb51d5c4e053732b41fb1d73ca5b983e273:app/(user)/layout.tsx

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD:app/(search page)/layout.tsx
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
=======
    return (
        <html lang="en">
            <body>
                <NavigationBar />
                {children}
                <Footer />
            </body>
        </html>
    );
>>>>>>> 04b78bb51d5c4e053732b41fb1d73ca5b983e273:app/(user)/layout.tsx
}
